---
title: "Reproducible Research Aims"
author: "Knight BSR"
date: "June 22, 2016"
output: 
  html_document: 
    theme: flatly
---

# Reproducible Research

As a collaborative team, Knight BSR and CRAB aim to increase reproducibility and transparancy in our research. This document serves as a record of reproducibility related tasks in progress and completed.

# Checklist

# Data storage

## Guidelines for storing data

- Data is stored on a shared server. The shared drive is accessible to all members and can be mounted on a local computer.

## Folder organization best practices

References:

- https://www.maxmasnick.com/analysis-org
- https://r-dir.com/blog/2013/11/folder-structure-for-data-analysis.html
- http://nicercode.github.io/blog/2013-04-05-projects/
- Sas specific: http://www2.sas.com/proceedings/forum2008/083-2008.pdf
- http://chance.amstat.org/2015/11/reproducible-reporting
- Gandrud 2013

## File naming best practices

References:

- https://library.stanford.edu/research/data-management-services/data-best-practices/best-practices-file-naming
- http://www.exadox.com/en/articles/file-naming-convention-ten-rules-best-practice

# Shared Code

# Training

- Introduction to reproducible research and goals in reproducible research were discussed and presented to BSR and BSR+CRAB. (12/2015, 04/2016, 06/2016)
- Participation in ASA Webinar "Enabling Reproducibility in Statistical Analyses Using R Markdown" (07/2016)
